spring:
  datasource:
    # 1. DB 주소: 메모리 모드 (끄면 데이터 날아감 - 테스트용으로 최고)
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      # 2. 웹 브라우저에서 DB 관리화면(H2 Console) 켜기
      enabled: true
      path: /h2-console
      
  jpa:
    # 3. 서버 켜질 때 Entity(자바 객체) 보고 테이블 '자동 생성' (오라클에선 직접 했었죠?)
    hibernate:
      ddl-auto: update
    
    # 4. 실행되는 SQL 쿼리를 로그에 보여줌 (디버깅용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true